// Code generated by protoc-gen-go. DO NOT EDIT.
// source: manifest.proto

package manifest

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Metadata_Type int32

const (
	Metadata_UNKNOWN Metadata_Type = 0
	Metadata_FILE    Metadata_Type = 1
	Metadata_SYMLINK Metadata_Type = 2
)

var Metadata_Type_name = map[int32]string{
	0: "UNKNOWN",
	1: "FILE",
	2: "SYMLINK",
}

var Metadata_Type_value = map[string]int32{
	"UNKNOWN": 0,
	"FILE":    1,
	"SYMLINK": 2,
}

func (x Metadata_Type) String() string {
	return proto.EnumName(Metadata_Type_name, int32(x))
}

func (Metadata_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0bb23f43f7afb4c1, []int{2, 0}
}

type Range struct {
	Offset               int64    `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Length               int64    `protobuf:"varint,3,opt,name=length,proto3" json:"length,omitempty"`
	BlobBytes            []byte   `protobuf:"bytes,4,opt,name=blob_bytes,json=blobBytes,proto3" json:"blob_bytes,omitempty"`
	DeprecatedBlobString string   `protobuf:"bytes,1,opt,name=deprecated_blob_string,json=deprecatedBlobString,proto3" json:"deprecated_blob_string,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Range) Reset()         { *m = Range{} }
func (m *Range) String() string { return proto.CompactTextString(m) }
func (*Range) ProtoMessage()    {}
func (*Range) Descriptor() ([]byte, []int) {
	return fileDescriptor_0bb23f43f7afb4c1, []int{0}
}

func (m *Range) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Range.Unmarshal(m, b)
}
func (m *Range) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Range.Marshal(b, m, deterministic)
}
func (m *Range) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Range.Merge(m, src)
}
func (m *Range) XXX_Size() int {
	return xxx_messageInfo_Range.Size(m)
}
func (m *Range) XXX_DiscardUnknown() {
	xxx_messageInfo_Range.DiscardUnknown(m)
}

var xxx_messageInfo_Range proto.InternalMessageInfo

func (m *Range) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *Range) GetLength() int64 {
	if m != nil {
		return m.Length
	}
	return 0
}

func (m *Range) GetBlobBytes() []byte {
	if m != nil {
		return m.BlobBytes
	}
	return nil
}

func (m *Range) GetDeprecatedBlobString() string {
	if m != nil {
		return m.DeprecatedBlobString
	}
	return ""
}

type Stream struct {
	Ranges               []*Range `protobuf:"bytes,1,rep,name=ranges,proto3" json:"ranges,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Stream) Reset()         { *m = Stream{} }
func (m *Stream) String() string { return proto.CompactTextString(m) }
func (*Stream) ProtoMessage()    {}
func (*Stream) Descriptor() ([]byte, []int) {
	return fileDescriptor_0bb23f43f7afb4c1, []int{1}
}

func (m *Stream) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Stream.Unmarshal(m, b)
}
func (m *Stream) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Stream.Marshal(b, m, deterministic)
}
func (m *Stream) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Stream.Merge(m, src)
}
func (m *Stream) XXX_Size() int {
	return xxx_messageInfo_Stream.Size(m)
}
func (m *Stream) XXX_DiscardUnknown() {
	xxx_messageInfo_Stream.DiscardUnknown(m)
}

var xxx_messageInfo_Stream proto.InternalMessageInfo

func (m *Stream) GetRanges() []*Range {
	if m != nil {
		return m.Ranges
	}
	return nil
}

type Metadata struct {
	Type                 Metadata_Type        `protobuf:"varint,1,opt,name=type,proto3,enum=manifest.Metadata_Type" json:"type,omitempty"`
	Creation             *timestamp.Timestamp `protobuf:"bytes,2,opt,name=creation,proto3" json:"creation,omitempty"`
	Modified             *timestamp.Timestamp `protobuf:"bytes,3,opt,name=modified,proto3" json:"modified,omitempty"`
	Mode                 uint32               `protobuf:"varint,4,opt,name=mode,proto3" json:"mode,omitempty"`
	LinkTarget           []byte               `protobuf:"bytes,5,opt,name=link_target,json=linkTarget,proto3" json:"link_target,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Metadata) Reset()         { *m = Metadata{} }
func (m *Metadata) String() string { return proto.CompactTextString(m) }
func (*Metadata) ProtoMessage()    {}
func (*Metadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_0bb23f43f7afb4c1, []int{2}
}

func (m *Metadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Metadata.Unmarshal(m, b)
}
func (m *Metadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Metadata.Marshal(b, m, deterministic)
}
func (m *Metadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Metadata.Merge(m, src)
}
func (m *Metadata) XXX_Size() int {
	return xxx_messageInfo_Metadata.Size(m)
}
func (m *Metadata) XXX_DiscardUnknown() {
	xxx_messageInfo_Metadata.DiscardUnknown(m)
}

var xxx_messageInfo_Metadata proto.InternalMessageInfo

func (m *Metadata) GetType() Metadata_Type {
	if m != nil {
		return m.Type
	}
	return Metadata_UNKNOWN
}

func (m *Metadata) GetCreation() *timestamp.Timestamp {
	if m != nil {
		return m.Creation
	}
	return nil
}

func (m *Metadata) GetModified() *timestamp.Timestamp {
	if m != nil {
		return m.Modified
	}
	return nil
}

func (m *Metadata) GetMode() uint32 {
	if m != nil {
		return m.Mode
	}
	return 0
}

func (m *Metadata) GetLinkTarget() []byte {
	if m != nil {
		return m.LinkTarget
	}
	return nil
}

type Content struct {
	Metadata             *Metadata `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Hash                 []byte    `protobuf:"bytes,3,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Content) Reset()         { *m = Content{} }
func (m *Content) String() string { return proto.CompactTextString(m) }
func (*Content) ProtoMessage()    {}
func (*Content) Descriptor() ([]byte, []int) {
	return fileDescriptor_0bb23f43f7afb4c1, []int{3}
}

func (m *Content) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Content.Unmarshal(m, b)
}
func (m *Content) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Content.Marshal(b, m, deterministic)
}
func (m *Content) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Content.Merge(m, src)
}
func (m *Content) XXX_Size() int {
	return xxx_messageInfo_Content.Size(m)
}
func (m *Content) XXX_DiscardUnknown() {
	xxx_messageInfo_Content.DiscardUnknown(m)
}

var xxx_messageInfo_Content proto.InternalMessageInfo

func (m *Content) GetMetadata() *Metadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *Content) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

type Entry struct {
	Path                 []byte   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Content              *Content `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Entry) Reset()         { *m = Entry{} }
func (m *Entry) String() string { return proto.CompactTextString(m) }
func (*Entry) ProtoMessage()    {}
func (*Entry) Descriptor() ([]byte, []int) {
	return fileDescriptor_0bb23f43f7afb4c1, []int{4}
}

func (m *Entry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Entry.Unmarshal(m, b)
}
func (m *Entry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Entry.Marshal(b, m, deterministic)
}
func (m *Entry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Entry.Merge(m, src)
}
func (m *Entry) XXX_Size() int {
	return xxx_messageInfo_Entry.Size(m)
}
func (m *Entry) XXX_DiscardUnknown() {
	xxx_messageInfo_Entry.DiscardUnknown(m)
}

var xxx_messageInfo_Entry proto.InternalMessageInfo

func (m *Entry) GetPath() []byte {
	if m != nil {
		return m.Path
	}
	return nil
}

func (m *Entry) GetContent() *Content {
	if m != nil {
		return m.Content
	}
	return nil
}

type EntrySet struct {
	Entries              []*Entry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EntrySet) Reset()         { *m = EntrySet{} }
func (m *EntrySet) String() string { return proto.CompactTextString(m) }
func (*EntrySet) ProtoMessage()    {}
func (*EntrySet) Descriptor() ([]byte, []int) {
	return fileDescriptor_0bb23f43f7afb4c1, []int{5}
}

func (m *EntrySet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EntrySet.Unmarshal(m, b)
}
func (m *EntrySet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EntrySet.Marshal(b, m, deterministic)
}
func (m *EntrySet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EntrySet.Merge(m, src)
}
func (m *EntrySet) XXX_Size() int {
	return xxx_messageInfo_EntrySet.Size(m)
}
func (m *EntrySet) XXX_DiscardUnknown() {
	xxx_messageInfo_EntrySet.DiscardUnknown(m)
}

var xxx_messageInfo_EntrySet proto.InternalMessageInfo

func (m *EntrySet) GetEntries() []*Entry {
	if m != nil {
		return m.Entries
	}
	return nil
}

type Page struct {
	Prefix []byte `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	// Types that are valid to be assigned to Descendents:
	//	*Page_Branch
	//	*Page_Entries
	Descendents          isPage_Descendents `protobuf_oneof:"descendents"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Page) Reset()         { *m = Page{} }
func (m *Page) String() string { return proto.CompactTextString(m) }
func (*Page) ProtoMessage()    {}
func (*Page) Descriptor() ([]byte, []int) {
	return fileDescriptor_0bb23f43f7afb4c1, []int{6}
}

func (m *Page) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Page.Unmarshal(m, b)
}
func (m *Page) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Page.Marshal(b, m, deterministic)
}
func (m *Page) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Page.Merge(m, src)
}
func (m *Page) XXX_Size() int {
	return xxx_messageInfo_Page.Size(m)
}
func (m *Page) XXX_DiscardUnknown() {
	xxx_messageInfo_Page.DiscardUnknown(m)
}

var xxx_messageInfo_Page proto.InternalMessageInfo

func (m *Page) GetPrefix() []byte {
	if m != nil {
		return m.Prefix
	}
	return nil
}

type isPage_Descendents interface {
	isPage_Descendents()
}

type Page_Branch struct {
	Branch *Stream `protobuf:"bytes,2,opt,name=branch,proto3,oneof"`
}

type Page_Entries struct {
	Entries *EntrySet `protobuf:"bytes,3,opt,name=entries,proto3,oneof"`
}

func (*Page_Branch) isPage_Descendents() {}

func (*Page_Entries) isPage_Descendents() {}

func (m *Page) GetDescendents() isPage_Descendents {
	if m != nil {
		return m.Descendents
	}
	return nil
}

func (m *Page) GetBranch() *Stream {
	if x, ok := m.GetDescendents().(*Page_Branch); ok {
		return x.Branch
	}
	return nil
}

func (m *Page) GetEntries() *EntrySet {
	if x, ok := m.GetDescendents().(*Page_Entries); ok {
		return x.Entries
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Page) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Page_Branch)(nil),
		(*Page_Entries)(nil),
	}
}

type HashedData struct {
	Hash                 []byte   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Data                 *Stream  `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HashedData) Reset()         { *m = HashedData{} }
func (m *HashedData) String() string { return proto.CompactTextString(m) }
func (*HashedData) ProtoMessage()    {}
func (*HashedData) Descriptor() ([]byte, []int) {
	return fileDescriptor_0bb23f43f7afb4c1, []int{7}
}

func (m *HashedData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HashedData.Unmarshal(m, b)
}
func (m *HashedData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HashedData.Marshal(b, m, deterministic)
}
func (m *HashedData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HashedData.Merge(m, src)
}
func (m *HashedData) XXX_Size() int {
	return xxx_messageInfo_HashedData.Size(m)
}
func (m *HashedData) XXX_DiscardUnknown() {
	xxx_messageInfo_HashedData.DiscardUnknown(m)
}

var xxx_messageInfo_HashedData proto.InternalMessageInfo

func (m *HashedData) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *HashedData) GetData() *Stream {
	if m != nil {
		return m.Data
	}
	return nil
}

type HashSet struct {
	Hashes               []*HashedData `protobuf:"bytes,1,rep,name=hashes,proto3" json:"hashes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *HashSet) Reset()         { *m = HashSet{} }
func (m *HashSet) String() string { return proto.CompactTextString(m) }
func (*HashSet) ProtoMessage()    {}
func (*HashSet) Descriptor() ([]byte, []int) {
	return fileDescriptor_0bb23f43f7afb4c1, []int{8}
}

func (m *HashSet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HashSet.Unmarshal(m, b)
}
func (m *HashSet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HashSet.Marshal(b, m, deterministic)
}
func (m *HashSet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HashSet.Merge(m, src)
}
func (m *HashSet) XXX_Size() int {
	return xxx_messageInfo_HashSet.Size(m)
}
func (m *HashSet) XXX_DiscardUnknown() {
	xxx_messageInfo_HashSet.DiscardUnknown(m)
}

var xxx_messageInfo_HashSet proto.InternalMessageInfo

func (m *HashSet) GetHashes() []*HashedData {
	if m != nil {
		return m.Hashes
	}
	return nil
}

func init() {
	proto.RegisterEnum("manifest.Metadata_Type", Metadata_Type_name, Metadata_Type_value)
	proto.RegisterType((*Range)(nil), "manifest.Range")
	proto.RegisterType((*Stream)(nil), "manifest.Stream")
	proto.RegisterType((*Metadata)(nil), "manifest.Metadata")
	proto.RegisterType((*Content)(nil), "manifest.Content")
	proto.RegisterType((*Entry)(nil), "manifest.Entry")
	proto.RegisterType((*EntrySet)(nil), "manifest.EntrySet")
	proto.RegisterType((*Page)(nil), "manifest.Page")
	proto.RegisterType((*HashedData)(nil), "manifest.HashedData")
	proto.RegisterType((*HashSet)(nil), "manifest.HashSet")
}

func init() {
	proto.RegisterFile("manifest.proto", fileDescriptor_0bb23f43f7afb4c1)
}

var fileDescriptor_0bb23f43f7afb4c1 = []byte{
	// 563 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x93, 0x5b, 0x6f, 0xd3, 0x4e,
	0x10, 0xc5, 0xeb, 0xc4, 0x4d, 0xdc, 0x71, 0xdb, 0x7f, 0xfe, 0xab, 0xaa, 0x58, 0x95, 0x50, 0x23,
	0x0b, 0x89, 0xd0, 0x22, 0x57, 0x84, 0xdb, 0x7b, 0xa0, 0x55, 0x4a, 0xdb, 0x80, 0x36, 0x45, 0xa8,
	0xbc, 0x44, 0xeb, 0x78, 0xec, 0x58, 0xc4, 0x6b, 0xcb, 0x1e, 0x24, 0xf2, 0x0d, 0x40, 0xe2, 0x43,
	0xa3, 0x5d, 0xdf, 0x10, 0x17, 0xf1, 0xb6, 0x7b, 0xe6, 0xcc, 0xce, 0xd9, 0x9f, 0xd7, 0xb0, 0x9f,
	0x08, 0x19, 0x87, 0x58, 0x90, 0x97, 0xe5, 0x29, 0xa5, 0xcc, 0xaa, 0xf7, 0x47, 0xc7, 0x51, 0x9a,
	0x46, 0x6b, 0x3c, 0xd3, 0xba, 0xff, 0x39, 0x3c, 0xa3, 0x38, 0xc1, 0x82, 0x44, 0x92, 0x95, 0x56,
	0xf7, 0xbb, 0x01, 0xdb, 0x5c, 0xc8, 0x08, 0xd9, 0x21, 0xf4, 0xd2, 0x30, 0x2c, 0x90, 0x9c, 0xce,
	0xd0, 0x18, 0x75, 0x79, 0xb5, 0x53, 0xfa, 0x1a, 0x65, 0x44, 0x2b, 0xa7, 0x5b, 0xea, 0xe5, 0x8e,
	0xdd, 0x07, 0xf0, 0xd7, 0xa9, 0xbf, 0xf0, 0x37, 0x84, 0x85, 0x63, 0x0e, 0x8d, 0xd1, 0x2e, 0xdf,
	0x51, 0xca, 0x44, 0x09, 0xec, 0x19, 0x1c, 0x06, 0x98, 0xe5, 0xb8, 0x14, 0x84, 0xc1, 0x42, 0x3b,
	0x0b, 0xca, 0x63, 0x19, 0x39, 0xc6, 0xd0, 0x18, 0xed, 0xf0, 0x83, 0xb6, 0x3a, 0x59, 0xa7, 0xfe,
	0x5c, 0xd7, 0xdc, 0x27, 0xd0, 0x9b, 0x53, 0x8e, 0x22, 0x61, 0x0f, 0xa1, 0x97, 0xab, 0x5c, 0x85,
	0x63, 0x0c, 0xbb, 0x23, 0x7b, 0xfc, 0x9f, 0xd7, 0x5c, 0x52, 0xe7, 0xe5, 0x55, 0xd9, 0xfd, 0xda,
	0x01, 0xeb, 0x06, 0x49, 0x04, 0x82, 0x04, 0x3b, 0x05, 0x93, 0x36, 0x19, 0xea, 0x19, 0xfb, 0xe3,
	0x7b, 0x6d, 0x4f, 0xed, 0xf0, 0x6e, 0x37, 0x19, 0x72, 0x6d, 0x62, 0x2f, 0xc0, 0x5a, 0xe6, 0x28,
	0x28, 0x4e, 0xa5, 0xbe, 0xb3, 0x3d, 0x3e, 0xf2, 0x4a, 0x5e, 0x5e, 0xcd, 0xcb, 0xbb, 0xad, 0x79,
	0xf1, 0xc6, 0xab, 0xfa, 0x92, 0x34, 0x88, 0xc3, 0x18, 0x03, 0xcd, 0xe4, 0x1f, 0x7d, 0xb5, 0x97,
	0x31, 0x30, 0x93, 0x34, 0x40, 0xcd, 0x6a, 0x8f, 0xeb, 0x35, 0x3b, 0x06, 0x7b, 0x1d, 0xcb, 0x4f,
	0x0b, 0x12, 0x79, 0x84, 0xe4, 0x6c, 0x6b, 0x8c, 0xa0, 0xa4, 0x5b, 0xad, 0xb8, 0x27, 0x60, 0xaa,
	0xc8, 0xcc, 0x86, 0xfe, 0xfb, 0xd9, 0xd5, 0xec, 0xed, 0x87, 0xd9, 0x60, 0x8b, 0x59, 0x60, 0x5e,
	0x5c, 0x5e, 0x9f, 0x0f, 0x0c, 0x25, 0xcf, 0xef, 0x6e, 0xae, 0x2f, 0x67, 0x57, 0x83, 0x8e, 0x7b,
	0x07, 0xfd, 0x57, 0xa9, 0x24, 0x94, 0xc4, 0x3c, 0xb0, 0x92, 0xea, 0xca, 0x1a, 0x86, 0x3d, 0x66,
	0xbf, 0xc3, 0xe0, 0x8d, 0x47, 0x65, 0x5b, 0x89, 0xa2, 0xfc, 0xc6, 0xbb, 0x5c, 0xaf, 0xdf, 0x98,
	0x56, 0x67, 0xd0, 0xe5, 0xa6, 0xaa, 0xbb, 0x53, 0xd8, 0x3e, 0x97, 0x94, 0x6f, 0x94, 0x31, 0x13,
	0xb4, 0xd2, 0x87, 0xee, 0x72, 0xbd, 0x66, 0xa7, 0xd0, 0x5f, 0x96, 0x73, 0x2b, 0x8e, 0xff, 0xb7,
	0xb3, 0xaa, 0x40, 0xbc, 0x76, 0xb8, 0xcf, 0xc1, 0xd2, 0x27, 0xcd, 0x91, 0xd8, 0x23, 0xe8, 0xa3,
	0xa4, 0x3c, 0xfe, 0xd3, 0x57, 0xd6, 0x26, 0x5e, 0xd7, 0xdd, 0x6f, 0x06, 0x98, 0xef, 0x44, 0xf9,
	0x4e, 0xb3, 0x1c, 0xc3, 0xf8, 0x4b, 0x15, 0xa1, 0xda, 0xb1, 0x13, 0xe8, 0xf9, 0xb9, 0x90, 0xcb,
	0x55, 0x95, 0x61, 0xd0, 0x1e, 0x55, 0x3e, 0xa9, 0xe9, 0x16, 0xaf, 0x1c, 0xcc, 0x6b, 0xe7, 0x76,
	0x7f, 0x85, 0x53, 0x87, 0x9b, 0x6e, 0x35, 0xc3, 0x27, 0x7b, 0x60, 0x07, 0x58, 0x2c, 0x51, 0x06,
	0x28, 0xa9, 0x70, 0x2f, 0x00, 0xa6, 0xa2, 0x58, 0x61, 0xf0, 0xfa, 0x67, 0x74, 0x46, 0x8b, 0x8e,
	0x3d, 0x00, 0x8d, 0xed, 0x6f, 0x51, 0x2a, 0xa8, 0x2f, 0xa1, 0xaf, 0xce, 0x51, 0x24, 0x1e, 0x43,
	0x4f, 0x35, 0x36, 0x20, 0x0e, 0xda, 0x96, 0x76, 0x14, 0xaf, 0x3c, 0x13, 0xf8, 0xd8, 0xfc, 0xe2,
	0x7e, 0x4f, 0xbf, 0xb9, 0xa7, 0x3f, 0x02, 0x00, 0x00, 0xff, 0xff, 0xdc, 0x35, 0xaa, 0x16, 0x05,
	0x04, 0x00, 0x00,
}
